### PR TITLE
First pass at 0.4.0 compatibility

### PR DESCRIPTION
**Pull request by josegonzalez**
I haven't tested this, but it should work well enough. Let me know how I can fix the pr to make it work.

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
Aside from the very minor point above, this looks awesome. Thanks!

**Comment by josegonzalez** [comment]
Fixed!

**Comment by josegonzalez** [comment]
The travis breaks are lint issues. I haven't used this plugin, so rather than attempt to fix the lints - which I barely understand - I'm going to leave that up to you to fix/ignore :)

**Comment by josegonzalez** [comment]
Bump :)

**Pull request merged**
